### PR TITLE
Updated to Swift 4

### PR DESCRIPTION
**Pull request by grahamcracker1234**
Also Added Support for Smart KeyPaths

### CODE REVIEW

**Comment by cornelcroi** [comment]
Hi. I'm trying to install this library to use it for a ios game, but no succes. Can you please tell me how to install this branch ? Thanks.

**Comment by cornelcroi** [comment]
Never mind, I got it. It works fine with swift 4.

**Comment by camiletti** [comment]
Thank you for the update @grahamcracker1234 !

**Comment by ataugeron** [comment]
Thanks for the update!

**Comment by grahamcracker1234** [comment]
@ataugeron No problem, I love this library, so I'm glad I can help out with it

**Pull request merged**
